version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./Mongo/data_gen:/data/db

  mongo-init:
    build: ./Mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./Mongo/data_json:/app/data_json

  scrapper:
    build: ./Scrapper
    depends_on:
      - mongo-init
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DATABASE=iphone_db
    volumes:
      - ./Mongo/data_json:/app/data_json

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  es-init:
    build: ./es-init
    depends_on:
      - elasticsearch

  flaskapp:
    build: ./Api
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      
volumes:
  mongo-data:
  elasticsearch-data:
